export const youTubeData = [
  {
    id: 1,
    image: "Momo",
    title: "MoMo Challenge",
    channelname: "Boki",
    views: 10000,
    time: 20,
  },
  {
    id: 2,
    image: "ooo",
    title: "Hindi songs",
    channelname: "Boki",
    views: 10000,
    time: 20,
  },
  {
    id: 3,
    image: "kkk",
    title: "Doraemon",
    channelname: "Boki",
    views: 10000,
    time: 20,
  },
  {
    id: 4,
    image: "kkl",
    title: "Demon Slayer",
    channelname: "Boki",
    views: 10000,
    time: 20,
  },
  {
    id: 5,
    image: "hhh",
    title: "Ginny",
    channelname: "Boki",
    views: 10000,
    time: 20,
  },
  {
    id: 6,
    image: "",
    title: "Meri bassai",
    channelname: "tarara",
    views: 10000,
    time: 20,
  },
];
